apiVersion: v2
name: fw-demo
description: A demo chart for FW Days DevOps 2024
type: application
version: 0.0.1
appVersion: "0.0.0"

dependencies:
  - name: monitoring
    version: 0.0.1
    repository: "file://../monitoring/"
